default_platform(:ios)

platform :ios do
  desc "Build and upload to TestFlight"
  lane :upload_testflight do |options|
    api_key = ENV.fetch('APPSTORE_API_KEY_CONTENT', '')
    
    # Create JSON key file
    File.write('../fastlane/api_key.json', {
      key_id: 'H3973L93M5',
      issuer_id: 'b2a00f88-3a8d-40d0-b148-1f1db92e10b7',
      key: api_key
    }.to_json)
    
    pilot(
      api_key_path: '../fastlane/api_key.json',
      app_platform: 'ios',
      app_identifier: 'com.ggsheng.UstiaGo',
      ipa: '../build/UstiaGo.ipa',
      skip_breaking_change_confirmation: true
    )
  end
end
